CREATE TABLE IF NOT EXISTS public.notifications (
  notification_id bigint generated by default as identity primary key,
  recipient_employee_id bigint not null references public.employees(id) on delete cascade,
  title text not null,
  description text,
  read_at timestamptz,
  created_at timestamptz not null default now()
);

CREATE INDEX IF NOT EXISTS idx_notifications_recipient_created
  ON public.notifications (recipient_employee_id, created_at desc);

ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS notifications_select_own ON public.notifications;
CREATE POLICY notifications_select_own ON public.notifications
  FOR SELECT TO authenticated
  USING (recipient_employee_id = (SELECT e.id FROM public.employees e WHERE lower(e.employee_email) = lower(auth.jwt() ->> 'email') ORDER BY e.id LIMIT 1));

DROP POLICY IF EXISTS notifications_update_own ON public.notifications;
CREATE POLICY notifications_update_own ON public.notifications
  FOR UPDATE TO authenticated
  USING (recipient_employee_id = (SELECT e.id FROM public.employees e WHERE lower(e.employee_email) = lower(auth.jwt() ->> 'email') ORDER BY e.id LIMIT 1))
  WITH CHECK (recipient_employee_id = (SELECT e.id FROM public.employees e WHERE lower(e.employee_email) = lower(auth.jwt() ->> 'email') ORDER BY e.id LIMIT 1));

DROP POLICY IF EXISTS notifications_delete_own ON public.notifications;
CREATE POLICY notifications_delete_own ON public.notifications
  FOR DELETE TO authenticated
  USING (recipient_employee_id = (SELECT e.id FROM public.employees e WHERE lower(e.employee_email) = lower(auth.jwt() ->> 'email') ORDER BY e.id LIMIT 1));

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime'
      AND schemaname = 'public'
      AND tablename = 'notifications'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.notifications;
  END IF;
END $$;

DO $$
DECLARE
  table_name text;
BEGIN
  FOREACH table_name IN ARRAY ARRAY['employees', 'employee_assignments', 'agent_assignments'] LOOP
    IF NOT EXISTS (
      SELECT 1 FROM pg_publication_tables
      WHERE pubname = 'supabase_realtime'
        AND schemaname = 'public'
        AND tablename = table_name
    ) THEN
      EXECUTE format('ALTER PUBLICATION supabase_realtime ADD TABLE public.%I', table_name);
    END IF;
  END LOOP;
END $$;
